### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by RaymondBalise** [CHOP-CGTInformatics/ggswim#25]
I tried to install ggswim today and I ran into a problems caused by  {`renv`}.   `renv::restore()` can't install all the dependencies because I run into:

```
#include <png.h>
         ^~~~~~~
1 error generated.
make: *** [devSVG.o] Error 1
ERROR: compilation failed for package ‘vdiffr’
```

I manually installed packages with `renv::install()` and I am able to bulid the package but the vignettes are missing.  I installed devtools and tried `devtools::install(build_vigngettes = TRUE)` and the package installs but the vignettes are missing.

Is there an ETA on the CRAN release?

**Comment by rsh52** [comment]
Hi @RaymondBalise! 

Mega apologies for the delayed response, had to change my notification settings. Will work on this ASAP!

> Is there an ETA on the CRAN release?

Might be a question for @skadauke, but I want to take a bit of time to explore the new [`ggplot2` 3.5](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0/) release changes which may have some nice optimizations for how I'm handling legend guides. Would be nice to get some more external testing and feedback of the package once I get your install issue sorted out.

**Comment by rsh52** [comment]
@RaymondBalise I updated how `vdiffr` is called, seems to install now on my machine and a colleagues. Can you confirm you're able to install?
