### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by ddsjoberg** [CHOP-CGTInformatics/ggswim#9]
- we need to decide a final API for the functions in the package
- @ddsjoberg will put together a proposal on an API using the suggested pbcseq dataset as the driving example.
    - we are in agreement (near agreement?) that `ggswim()` will construct the lanes, and each marker will be added separately with calls to `+ add_marker()`
- @ddsjoberg will review the current code internals and review with @rsh52 anything that could be modified to be more clear or brought inline with standard practices.
- @rsh52 what else did I miss here!?

**Comment by rsh52** [comment]
Looks pretty good! 

A general review of the process for assigning legend order and how/where this should get implemented with mindfulness to `add_markers()` will also be helpful. And whether we want to continue relying on `ggplot2::ggplot_build()` to help with this or not.

Another API consideration is how to treat missing data/data not specifically called out in an event stream. Ex: "No CRS" being a default value for missingness in the README. We had discussed what `ggswim()` should be able to automatically determine from a dataset.

**Comment by rsh52** [comment]
House cleaning, considering this closed ✅
